version: 2.1

orbs:
  docker: circleci/docker@0.5.2

jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/Dev25/mcrouter_exporter
    steps:
      - checkout
      - run: go get github.com/smartystreets/goconvey
      - run: go test -v ./...

  build:
    executor: default
    steps:
      - docker/publish:
          image: quay.io/dev25/mcrouter_exporter
          tag: :$CIRCLE_BRANCH-$CIRCLE_SHA1
          registry: quay.io


workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
